name: Deploy W5 - Hello World

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-deploy-cdk.yaml
    with:
      project_directory: week5/1-hello-world
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
