name: Deploy W6 - FlightAI Customer Service

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-deploy-cdk.yaml
    with:
      project_directory: week6/1-flightai-customer-service
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
