name: Deploy Guardrails

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-deploy-cdk.yaml
    with:
      project_directory: week6/2-guardrails
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}