name: Deploy W7 - Digital Twin Revisited

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-deploy-cdk.yaml
    with:
      project_directory: week7/2-digital-twin-revisited
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
