name: Deploy W7 - S3 Vectors

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-deploy-cdk.yaml
    with:
      project_directory: week7/1-s3-vectors
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
